#!/bin/sh

#  "dlr" - Dynamic Library Redux
#  Copyright 2020 Mark Hubbard, a.k.a. "TheMarkitecht"
#  http://www.TheMarkitecht.com
#   
#  Project home:  http://github.com/TheMarkitecht/dlr
#  dlr is an extension for Jim Tcl (http://jim.tcl.tk/)
#  dlr may be easily pronounced as "dealer".
#   
#  This file is part of dlr.
#   
#  dlr is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#   
#  dlr is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Lesser General Public License for more details.
#   
#  You should have received a copy of the GNU Lesser General Public License
#  along with dlr.  If not, see <https://www.gnu.org/licenses/>.

set -e
set -x

# builder settings
project=`pwd`
optim=0
compile="-I.  -I../../jimsh    -pipe -g3 -O$optim -Wall -fPIC -std=c11 -c"
linkSO="-pipe -g3 -O$optim -Wall -fPIC -std=c11 -Wl,--export-dynamic  -shared"

# build "dlr" extension for Jim.
cd $project/dlrNative-src
gcc $compile -o dlrNative.o  dlrNative.c
gcc $linkSO -o dlrNative.so  dlrNative.o  /usr/lib/x86_64-linux-gnu/libffi.a 

# build testLib.so
cd $project/testLib-src
gcc $compile -o testLib.o  testLib.c
gcc $linkSO -o testLib.so  testLib.o 

# run automated tests
cd $project
export JIMLIB=$project/dlr:$project/dlrNative-src
./jimsh  test.tcl

# check for memory leak
valgrind  -q  --leak-check=full  --leak-resolution=high  \
    --show-leak-kinds=definite,possible  --errors-for-leak-kinds=definite,possible  \
    ./jimsh  test.tcl

# test again with refreshMeta left off (the default).  that's a different code path.
./jimsh  test.tcl  1000000

# speed benchmark
# ./jimsh  test.tcl  30000000
