#!/bin/sh
set -e
set -x

optim=0
compile="-I.  -I../jimsh    -pipe -g3 -O$optim -Wall -fPIC -std=c11 -c"
link="-pipe -g3 -O$optim -Wall -fPIC -std=c11 -Wl,--export-dynamic  -shared"

# "dlr" extension for Jim.
gcc $compile -o dlrNative.o  dlrNative.c
gcc $link -o dlrNative.so  dlrNative.o  /usr/lib/x86_64-linux-gnu/libffi.a 

# dlrTestLib.so
gcc $compile -o dlrTestLib.o  dlrTestLib.c
gcc $link -o dlrTestLib.so  dlrTestLib.o 

# test runs
./jimsh  test.tcl

valgrind  -q  --leak-check=full  --leak-resolution=high  \
    --show-leak-kinds=definite,possible  --errors-for-leak-kinds=definite,possible  \
    ./jimsh  test.tcl

# time ./jimsh bench.tcl
